[tool.isort]
force_single_line = true
profile = "black"
skip = [
	".git",
	".mypy_cache",
	".pytest_cache",
	".venv",
	"__pycache__",
]

[tool.vulture]
exclude = [
	".git",
	".mypy_cache",
	".pytest_cache",
	".venv",
	"__pycache__",
]
min_confidence = 100
