version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  py2lint:
    executor:
      name: python/default
      tag: 2.7.18
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: make py2lint
  py3lint:
    executor:
      name: python/default
      tag: 3.7.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-py3lint.txt
      - run: make py3lint
  test:
    executor:
      name: python/default
      tag: 2.7.18
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: run tests
          command: |
            mkdir test-results
            pytest --junitxml=test-results/report.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  main:
    jobs:
      - test
      - py2lint
      - py3lint
