version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  lint:
    executor:
      name: python/default
      tag: 3.7.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: make lint
  test:
    executor:
      name: python/default
      tag: 3.7.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: run tests
          command: |
            mkdir test-results
            pytest --junitxml=test-results/report.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  main:
    jobs:
      - test
      - lint
